disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: ''

menu:
- {name: 'Home', path: '.', url: 'index.html'}
- {name: 'Approach', path: 'menu', url: 'approach.html'}
- {name: 'Case Study', path: 'menu', url: 'case.html'}
- {name: 'Applications', path: 'menu', url: 'applications.html'}
- {name: 'Related Research', path: 'menu', url: 'related.html'}
- {name: 'Alternative Methods', path: 'menu', url: 'methods.html'}

social:
- {icon: 'github', link: 'https://www.github.com/sbstn-gbl/p2v-map'}
- {icon: 'envelope', link: 'mailto:gabel@rsm.nl'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'
sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy:'
post_date_prefix: 'Written on'
